import { SKILL_RESOURCES } from "../data/skillResources";
import { SKILL_META } from "../data/skillRoadmapMeta";

const DEFAULT_RESOURCES = [
  { name: "freeCodeCamp", url: "https://www.freecodecamp.org/" },
  { name: "MDN Web Docs", url: "https://developer.mozilla.org/" },
  { name: "YouTube", url: "https://www.youtube.com/" },
];

function buildLearningPath(missingSkills) {
  const missingLower = new Set(missingSkills.map((s) => s.toLowerCase()));
  const visited = new Set();
  const path = [];

  function dfs(skill) {
    const key = skill.toLowerCase();
    if (visited.has(key)) return;
    visited.add(key);
    const prereq = SKILL_META[skill]?.prerequisites || [];
    for (const p of prereq) {
      const pk = p.toLowerCase();
      if (missingLower.has(pk)) {
        const original = missingSkills.find((x) => x.toLowerCase() === pk);
        if (original) dfs(original);
      }
    }
    path.push(skill);
  }

  for (const s of missingSkills) dfs(s);

  const seen = new Set();
  return path.filter((s) => {
    const k = s.toLowerCase();
    if (seen.has(k)) return false;
    seen.add(k);
    return true;
  });
}

function StepBadge({ num }) {
  return (
    <div className="absolute -left-3 top-6 h-8 w-8 rounded-full flex items-center justify-center text-xs font-black shadow-lg"
         style={{ background: "var(--tx-primary)", color: "var(--bg-main)" }}>
      {num}
    </div>
  );
}

function ResourceCard({ r }) {
  return (
    <a href={r.url} target="_blank" rel="noreferrer"
       className="flex flex-col justify-between rounded-xl p-4 transition-all hover:shadow-md group/link"
       style={{ background: "var(--bg-card)", border: "1px solid var(--bd-default)" }}>
      <div className="text-sm font-bold transition-colors group-hover/link:text-blue-500"
           style={{ color: "var(--tx-primary)" }}>
        {r.name}
      </div>
      <div className="text-[10px] truncate mt-1" style={{ color: "var(--tx-muted)" }}>
        {(() => { try { return new URL(r.url).hostname; } catch { return r.url; } })()}
      </div>
    </a>
  );
}

export default function Roadmap({ missingSkills, aiRoadmap = null, aiAnalysis = null }) {
  if (!missingSkills || missingSkills.length === 0) return null;

  const isAI = Array.isArray(aiRoadmap) && aiRoadmap.length > 0;

  const wrapperStyle = {
    background: "var(--bg-card)",
    border: "1px solid var(--bd-default)",
    borderRadius: "1.5rem",
  };

  const itemStyle = {
    background: "var(--bg-surface)",
    border: "1px solid var(--bd-default)",
    borderRadius: "1rem",
  };

  if (isAI) {
    return (
      <div className="p-8 shadow-sm space-y-8 transition-colors duration-300" style={wrapperStyle}>
        <div className="space-y-3">
          <div className="flex items-center gap-2">
            <h3 className="text-2xl font-black tracking-tight" style={{ color: "var(--tx-primary)" }}>
              AI-Generated Learning Roadmap
            </h3>
            <span className="text-[10px] font-extrabold px-2.5 py-1 rounded-full"
                  style={{ background: "rgba(124,58,237,0.12)", color: "#8b5cf6", border: "1px solid rgba(124,58,237,0.25)" }}>
              AI
            </span>
          </div>
          <p className="text-sm max-w-2xl leading-relaxed" style={{ color: "var(--tx-secondary)" }}>
            Personalized learning path generated by AI based on your skills and target role.
          </p>

          {aiAnalysis && (
            <div className="mt-4 p-5 rounded-2xl space-y-4"
                 style={{ background: "rgba(59,130,246,0.05)", border: "1px solid rgba(59,130,246,0.15)" }}>
              <p className="text-sm leading-relaxed" style={{ color: "var(--tx-primary)" }}>
                {aiAnalysis.summary}
              </p>
              <div className="flex flex-wrap gap-6">
                {aiAnalysis.strengths?.length > 0 && (
                  <div>
                    <div className="text-[10px] font-black uppercase tracking-widest mb-1.5" style={{ color: "#10b981" }}>
                      Your Strengths
                    </div>
                    <div className="flex flex-wrap gap-1.5">
                      {aiAnalysis.strengths.map((s) => (
                        <span key={s} className="text-[10px] font-bold px-2.5 py-1 rounded-lg"
                              style={{ background: "rgba(16,185,129,0.08)", border: "1px solid rgba(16,185,129,0.25)", color: "#10b981" }}>
                          {s}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
                {aiAnalysis.estimatedWeeks > 0 && (
                  <div>
                    <div className="text-[10px] font-black uppercase tracking-widest mb-1.5" style={{ color: "#3b82f6" }}>
                      Estimated Time
                    </div>
                    <div className="text-sm font-bold" style={{ color: "var(--tx-primary)" }}>
                      ~{aiAnalysis.estimatedWeeks} weeks
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>

        <div className="space-y-6">
          {aiRoadmap.map((item, idx) => (
            <div key={item.skill} className="relative group p-6 space-y-5 transition-all"
                 style={itemStyle}>
              <StepBadge num={idx + 1} />
              <div className="pl-6 space-y-5">
                <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                  <h4 className="text-xl font-bold" style={{ color: "var(--tx-primary)" }}>{item.skill}</h4>
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] font-black px-3 py-1 rounded-full uppercase tracking-widest"
                          style={{ background: "rgba(59,130,246,0.08)", border: "1px solid rgba(59,130,246,0.2)", color: "#3b82f6" }}>
                      ~{item.estimatedDays} days
                    </span>
                    <span className="text-[10px] font-black px-3 py-1 rounded-full uppercase tracking-widest"
                          style={{ background: "rgba(124,58,237,0.08)", border: "1px solid rgba(124,58,237,0.2)", color: "#8b5cf6" }}>
                      Priority #{item.priority}
                    </span>
                  </div>
                </div>

                {item.why && (
                  <p className="text-sm leading-relaxed" style={{ color: "var(--tx-secondary)" }}>{item.why}</p>
                )}

                <div className="grid gap-3 sm:grid-cols-3">
                  {item.resources.map((r) => <ResourceCard key={r.url} r={r} />)}
                </div>

                <div className="grid gap-4 sm:grid-cols-2">
                  <div className="space-y-2">
                    <div className="text-[10px] font-black uppercase tracking-widest" style={{ color: "var(--tx-muted)" }}>AI Tip</div>
                    <div className="text-xs italic leading-relaxed" style={{ color: "var(--tx-secondary)" }}>
                      "{item.tip}"
                    </div>
                  </div>
                  <div className="space-y-2 p-3 rounded-xl"
                       style={{ background: "rgba(59,130,246,0.05)", border: "1px solid rgba(59,130,246,0.15)" }}>
                    <div className="text-[10px] font-black uppercase tracking-widest" style={{ color: "#3b82f6" }}>Mini Project</div>
                    <div className="text-xs font-bold" style={{ color: "var(--tx-primary)" }}>{item.miniProject}</div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }

  // Static fallback
  const ordered = buildLearningPath(missingSkills);

  return (
    <div className="p-8 shadow-sm space-y-8 transition-colors duration-300" style={wrapperStyle}>
      <div className="space-y-2">
        <h3 className="text-2xl font-black tracking-tight" style={{ color: "var(--tx-primary)" }}>
          Roadmap: Master Your Path
        </h3>
        <p className="text-sm max-w-xl leading-relaxed" style={{ color: "var(--tx-secondary)" }}>
          Follow this optimized sequence (prerequisites first). Each module contains vetted resources,
          strategic advice, and a practical mini-project.
        </p>
      </div>

      <div className="space-y-6">
        {ordered.map((skill, idx) => {
          const resources = SKILL_RESOURCES[skill] || DEFAULT_RESOURCES;
          const meta = SKILL_META[skill];

          return (
            <div key={skill} className="relative group p-6 space-y-6 transition-all" style={itemStyle}>
              <StepBadge num={idx + 1} />
              <div className="pl-6 space-y-6">
                <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                  <h4 className="text-xl font-bold" style={{ color: "var(--tx-primary)" }}>{skill}</h4>
                  <div className="flex items-center gap-2 px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-widest"
                       style={{ background: "rgba(59,130,246,0.08)", border: "1px solid rgba(59,130,246,0.2)", color: "#3b82f6" }}>
                    Learn Now
                  </div>
                </div>

                <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                  {resources.slice(0, 3).map((r) => <ResourceCard key={r.url} r={r} />)}
                </div>

                <div className="grid gap-4 sm:grid-cols-2 pt-2">
                  <div className="space-y-2">
                    <div className="text-[10px] font-black uppercase tracking-widest" style={{ color: "var(--tx-muted)" }}>Strategic Tip</div>
                    <div className="text-xs italic leading-relaxed" style={{ color: "var(--tx-secondary)" }}>
                      "{meta?.tip || "Focus on fundamental concepts before moving to complex implementation."}"
                    </div>
                  </div>
                  <div className="space-y-2 p-3 rounded-xl"
                       style={{ background: "rgba(59,130,246,0.05)", border: "1px solid rgba(59,130,246,0.15)" }}>
                    <div className="text-[10px] font-black uppercase tracking-widest" style={{ color: "#3b82f6" }}>Mini Project</div>
                    <div className="text-xs font-bold" style={{ color: "var(--tx-primary)" }}>
                      {meta?.miniProject || "Build a small CLI or web tool to apply this skill."}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
